//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameProtocol.LOG.proto
namespace GameProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRole")]
  public partial class CreateRole : global::ProtoBuf.IExtensible
  {
    public CreateRole() {}
    

    private long _iEventID = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iEventID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long iEventID
    {
      get { return _iEventID; }
      set { _iEventID = value; }
    }

    private uint _uin = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uin
    {
      get { return _uin; }
      set { _uin = value; }
    }

    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }

    private uint _iClientIP = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"iClientIP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint iClientIP
    {
      get { return _iClientIP; }
      set { _iClientIP = value; }
    }

    private string _strRoleName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"strRoleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strRoleName
    {
      get { return _strRoleName; }
      set { _strRoleName = value; }
    }

    private uint _iGender = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"iGender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint iGender
    {
      get { return _iGender; }
      set { _iGender = value; }
    }

    private uint _iAppType = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"iAppType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint iAppType
    {
      get { return _iAppType; }
      set { _iAppType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteRole")]
  public partial class DeleteRole : global::ProtoBuf.IExtensible
  {
    public DeleteRole() {}
    

    private long _iEventID = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iEventID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long iEventID
    {
      get { return _iEventID; }
      set { _iEventID = value; }
    }

    private uint _uin = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uin
    {
      get { return _uin; }
      set { _uin = value; }
    }

    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }

    private uint _iClientIP = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"iClientIP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint iClientIP
    {
      get { return _iClientIP; }
      set { _iClientIP = value; }
    }

    private string _strRoleName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"strRoleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strRoleName
    {
      get { return _strRoleName; }
      set { _strRoleName = value; }
    }

    private uint _iGender = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"iGender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint iGender
    {
      get { return _iGender; }
      set { _iGender = value; }
    }

    private uint _iRoleLevel = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"iRoleLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint iRoleLevel
    {
      get { return _iRoleLevel; }
      set { _iRoleLevel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogDetail")]
  public partial class LogDetail : global::ProtoBuf.IExtensible
  {
    public LogDetail() {}
    

    private CreateRole _stCreateRole = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stCreateRole", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public CreateRole stCreateRole
    {
      get { return _stCreateRole; }
      set { _stCreateRole = value; }
    }

    private DeleteRole _stDeleteRole = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stDeleteRole", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public DeleteRole stDeleteRole
    {
      get { return _stDeleteRole; }
      set { _stDeleteRole = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogPkg")]
  public partial class LogPkg : global::ProtoBuf.IExtensible
  {
    public LogPkg() {}
    

    private uint _cmd = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }

    private LogDetail _details = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"details", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public LogDetail details
    {
      get { return _details; }
      set { _details = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"LogMsgID")]
    public enum LogMsgID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_CREATEROLE", Value=1001)]
      LOG_CREATEROLE = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_DELETEROLE", Value=1002)]
      LOG_DELETEROLE = 1002
    }
  
}