//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameProtocol.Mail.proto
namespace GameProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OneAttachment")]
  public partial class OneAttachment : global::ProtoBuf.IExtensible
  {
    public OneAttachment() {}
    

    private int _iDropType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iDropType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iDropType
    {
      get { return _iDropType; }
      set { _iDropType = value; }
    }

    private int _iDropId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iDropId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iDropId
    {
      get { return _iDropId; }
      set { _iDropId = value; }
    }

    private int _iDropNum = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iDropNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iDropNum
    {
      get { return _iDropNum; }
      set { _iDropNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailAttachment")]
  public partial class MailAttachment : global::ProtoBuf.IExtensible
  {
    public MailAttachment() {}
    
    private readonly global::System.Collections.Generic.List<OneAttachment> _stAttachments = new global::System.Collections.Generic.List<OneAttachment>();
    [global::ProtoBuf.ProtoMember(1, Name=@"stAttachments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OneAttachment> stAttachments
    {
      get { return _stAttachments; }
    }
  

    private int _iSourceType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iSourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iSourceType
    {
      get { return _iSourceType; }
      set { _iSourceType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OneMail")]
  public partial class OneMail : global::ProtoBuf.IExtensible
  {
    public OneMail() {}
    

    private int _iMailId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iMailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iMailId
    {
      get { return _iMailId; }
      set { _iMailId = value; }
    }

    private int _iuin = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iuin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iuin
    {
      get { return _iuin; }
      set { _iuin = value; }
    }

    private int _iRoleId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iRoleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRoleId
    {
      get { return _iRoleId; }
      set { _iRoleId = value; }
    }

    private int _iMailType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"iMailType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iMailType
    {
      get { return _iMailType; }
      set { _iMailType = value; }
    }

    private int _iSendUin = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"iSendUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iSendUin
    {
      get { return _iSendUin; }
      set { _iSendUin = value; }
    }

    private int _iSendRoleId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"iSendRoleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iSendRoleId
    {
      get { return _iSendRoleId; }
      set { _iSendRoleId = value; }
    }

    private string _strSenderName = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"strSenderName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strSenderName
    {
      get { return _strSenderName; }
      set { _strSenderName = value; }
    }

    private int _iRecvUin = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"iRecvUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRecvUin
    {
      get { return _iRecvUin; }
      set { _iRecvUin = value; }
    }

    private int _iRecvRoleId = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"iRecvRoleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRecvRoleId
    {
      get { return _iRecvRoleId; }
      set { _iRecvRoleId = value; }
    }

    private string _strRecverName = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"strRecverName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strRecverName
    {
      get { return _strRecverName; }
      set { _strRecverName = value; }
    }

    private string _strTitle = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"strTitle", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strTitle
    {
      get { return _strTitle; }
      set { _strTitle = value; }
    }

    private string _strContent = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"strContent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strContent
    {
      get { return _strContent; }
      set { _strContent = value; }
    }

    private int _iSendDateTime = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"iSendDateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iSendDateTime
    {
      get { return _iSendDateTime; }
      set { _iSendDateTime = value; }
    }

    private int _iReadDateTime = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"iReadDateTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iReadDateTime
    {
      get { return _iReadDateTime; }
      set { _iReadDateTime = value; }
    }

    private int _iReadTag = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"iReadTag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iReadTag
    {
      get { return _iReadTag; }
      set { _iReadTag = value; }
    }

    private int _iRecvTag = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"iRecvTag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRecvTag
    {
      get { return _iRecvTag; }
      set { _iRecvTag = value; }
    }

    private int _iAttachMentTag = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"iAttachMentTag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iAttachMentTag
    {
      get { return _iAttachMentTag; }
      set { _iAttachMentTag = value; }
    }

    private int _iAttachMentNum = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"iAttachMentNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iAttachMentNum
    {
      get { return _iAttachMentNum; }
      set { _iAttachMentNum = value; }
    }

    private MailAttachment _stMailAttachment = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"stMailAttachment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MailAttachment stMailAttachment
    {
      get { return _stMailAttachment; }
      set { _stMailAttachment = value; }
    }

    private int _iDeleteTag = default(int);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"iDeleteTag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iDeleteTag
    {
      get { return _iDeleteTag; }
      set { _iDeleteTag = value; }
    }

    private int _iMark = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"iMark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iMark
    {
      get { return _iMark; }
      set { _iMark = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_FetchMailList_Request")]
  public partial class Mail_FetchMailList_Request : global::ProtoBuf.IExtensible
  {
    public Mail_FetchMailList_Request() {}
    

    private int _iUin = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUin
    {
      get { return _iUin; }
      set { _iUin = value; }
    }

    private int _iRole = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iRole", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRole
    {
      get { return _iRole; }
      set { _iRole = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_FetchMailList_Response")]
  public partial class Mail_FetchMailList_Response : global::ProtoBuf.IExtensible
  {
    public Mail_FetchMailList_Response() {}
    

    private int _iUin = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUin
    {
      get { return _iUin; }
      set { _iUin = value; }
    }

    private int _iRole = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iRole", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRole
    {
      get { return _iRole; }
      set { _iRole = value; }
    }
    private readonly global::System.Collections.Generic.List<OneMail> _stMailList = new global::System.Collections.Generic.List<OneMail>();
    [global::ProtoBuf.ProtoMember(3, Name=@"stMailList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OneMail> stMailList
    {
      get { return _stMailList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_FetchNewMailList_Request")]
  public partial class Mail_FetchNewMailList_Request : global::ProtoBuf.IExtensible
  {
    public Mail_FetchNewMailList_Request() {}
    

    private int _iUin = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUin
    {
      get { return _iUin; }
      set { _iUin = value; }
    }

    private int _iRole = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iRole", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRole
    {
      get { return _iRole; }
      set { _iRole = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_FetchNewMailList_Response")]
  public partial class Mail_FetchNewMailList_Response : global::ProtoBuf.IExtensible
  {
    public Mail_FetchNewMailList_Response() {}
    

    private int _iUin = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUin
    {
      get { return _iUin; }
      set { _iUin = value; }
    }

    private int _iRole = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iRole", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRole
    {
      get { return _iRole; }
      set { _iRole = value; }
    }
    private readonly global::System.Collections.Generic.List<OneMail> _stMailList = new global::System.Collections.Generic.List<OneMail>();
    [global::ProtoBuf.ProtoMember(3, Name=@"stMailList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OneMail> stMailList
    {
      get { return _stMailList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_CreateNewMail_Request")]
  public partial class Mail_CreateNewMail_Request : global::ProtoBuf.IExtensible
  {
    public Mail_CreateNewMail_Request() {}
    

    private OneMail _stMail = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stMail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OneMail stMail
    {
      get { return _stMail; }
      set { _stMail = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_CreateNewMail_Response")]
  public partial class Mail_CreateNewMail_Response : global::ProtoBuf.IExtensible
  {
    public Mail_CreateNewMail_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }

    private OneMail _stMail = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stMail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OneMail stMail
    {
      get { return _stMail; }
      set { _stMail = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_SendMail_Request")]
  public partial class Mail_SendMail_Request : global::ProtoBuf.IExtensible
  {
    public Mail_SendMail_Request() {}
    
    private readonly global::System.Collections.Generic.List<OneMail> _stMailList = new global::System.Collections.Generic.List<OneMail>();
    [global::ProtoBuf.ProtoMember(1, Name=@"stMailList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OneMail> stMailList
    {
      get { return _stMailList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_SendMail_Response")]
  public partial class Mail_SendMail_Response : global::ProtoBuf.IExtensible
  {
    public Mail_SendMail_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }
    private readonly global::System.Collections.Generic.List<OneMail> _stMailList = new global::System.Collections.Generic.List<OneMail>();
    [global::ProtoBuf.ProtoMember(2, Name=@"stMailList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OneMail> stMailList
    {
      get { return _stMailList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_DeleteMail_Request")]
  public partial class Mail_DeleteMail_Request : global::ProtoBuf.IExtensible
  {
    public Mail_DeleteMail_Request() {}
    
    private readonly global::System.Collections.Generic.List<int> _stMailIdList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"stMailIdList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> stMailIdList
    {
      get { return _stMailIdList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_DeleteMail_Response")]
  public partial class Mail_DeleteMail_Response : global::ProtoBuf.IExtensible
  {
    public Mail_DeleteMail_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _stMailList = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"stMailList", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> stMailList
    {
      get { return _stMailList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_UpdateMail_Request")]
  public partial class Mail_UpdateMail_Request : global::ProtoBuf.IExtensible
  {
    public Mail_UpdateMail_Request() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_UpdateMail_Response")]
  public partial class Mail_UpdateMail_Response : global::ProtoBuf.IExtensible
  {
    public Mail_UpdateMail_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ApplyMailAttachment")]
  public partial class ApplyMailAttachment : global::ProtoBuf.IExtensible
  {
    public ApplyMailAttachment() {}
    

    private int _iMailId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iMailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iMailId
    {
      get { return _iMailId; }
      set { _iMailId = value; }
    }

    private MailAttachment _stMailAttachMents = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stMailAttachMents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MailAttachment stMailAttachMents
    {
      get { return _stMailAttachMents; }
      set { _stMailAttachMents = value; }
    }

    private int _iMailType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iMailType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iMailType
    {
      get { return _iMailType; }
      set { _iMailType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_ApplyAttachment_Request")]
  public partial class Mail_ApplyAttachment_Request : global::ProtoBuf.IExtensible
  {
    public Mail_ApplyAttachment_Request() {}
    
    private readonly global::System.Collections.Generic.List<ApplyMailAttachment> _stApplyMailAttachMents = new global::System.Collections.Generic.List<ApplyMailAttachment>();
    [global::ProtoBuf.ProtoMember(1, Name=@"stApplyMailAttachMents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ApplyMailAttachment> stApplyMailAttachMents
    {
      get { return _stApplyMailAttachMents; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_ApplyAttachment_Response")]
  public partial class Mail_ApplyAttachment_Response : global::ProtoBuf.IExtensible
  {
    public Mail_ApplyAttachment_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _iMailIds = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"iMailIds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> iMailIds
    {
      get { return _iMailIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_FetchMailList_Request")]
  public partial class MailDB_FetchMailList_Request : global::ProtoBuf.IExtensible
  {
    public MailDB_FetchMailList_Request() {}
    

    private int _iUin = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUin
    {
      get { return _iUin; }
      set { _iUin = value; }
    }

    private int _iRole = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iRole", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRole
    {
      get { return _iRole; }
      set { _iRole = value; }
    }

    private int _iRecvTag = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iRecvTag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRecvTag
    {
      get { return _iRecvTag; }
      set { _iRecvTag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_FetchMailList_Response")]
  public partial class MailDB_FetchMailList_Response : global::ProtoBuf.IExtensible
  {
    public MailDB_FetchMailList_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }

    private int _iUin = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUin
    {
      get { return _iUin; }
      set { _iUin = value; }
    }

    private int _iRole = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iRole", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRole
    {
      get { return _iRole; }
      set { _iRole = value; }
    }
    private readonly global::System.Collections.Generic.List<OneMail> _stMailList = new global::System.Collections.Generic.List<OneMail>();
    [global::ProtoBuf.ProtoMember(4, Name=@"stMailList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OneMail> stMailList
    {
      get { return _stMailList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_FetchOneMail_Request")]
  public partial class MailDB_FetchOneMail_Request : global::ProtoBuf.IExtensible
  {
    public MailDB_FetchOneMail_Request() {}
    

    private int _iUin = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUin
    {
      get { return _iUin; }
      set { _iUin = value; }
    }

    private int _iRole = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iRole", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRole
    {
      get { return _iRole; }
      set { _iRole = value; }
    }

    private int _iMailId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iMailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iMailId
    {
      get { return _iMailId; }
      set { _iMailId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_FetchOneMail_Response")]
  public partial class MailDB_FetchOneMail_Response : global::ProtoBuf.IExtensible
  {
    public MailDB_FetchOneMail_Response() {}
    

    private OneMail _stMail = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stMail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OneMail stMail
    {
      get { return _stMail; }
      set { _stMail = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_CheckNewMailList_Request")]
  public partial class MailDB_CheckNewMailList_Request : global::ProtoBuf.IExtensible
  {
    public MailDB_CheckNewMailList_Request() {}
    

    private int _iUin = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUin
    {
      get { return _iUin; }
      set { _iUin = value; }
    }

    private int _iRole = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iRole", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRole
    {
      get { return _iRole; }
      set { _iRole = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_CheckNewMailList_Response")]
  public partial class MailDB_CheckNewMailList_Response : global::ProtoBuf.IExtensible
  {
    public MailDB_CheckNewMailList_Response() {}
    

    private int _iUin = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUin
    {
      get { return _iUin; }
      set { _iUin = value; }
    }

    private int _iRole = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iRole", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRole
    {
      get { return _iRole; }
      set { _iRole = value; }
    }
    private readonly global::System.Collections.Generic.List<OneMail> _stMailList = new global::System.Collections.Generic.List<OneMail>();
    [global::ProtoBuf.ProtoMember(3, Name=@"stMailList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OneMail> stMailList
    {
      get { return _stMailList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_FetchMailNum_Request")]
  public partial class MailDB_FetchMailNum_Request : global::ProtoBuf.IExtensible
  {
    public MailDB_FetchMailNum_Request() {}
    

    private int _iUin = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUin
    {
      get { return _iUin; }
      set { _iUin = value; }
    }

    private int _iRole = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iRole", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRole
    {
      get { return _iRole; }
      set { _iRole = value; }
    }

    private int _iNormalLiveTime = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iNormalLiveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iNormalLiveTime
    {
      get { return _iNormalLiveTime; }
      set { _iNormalLiveTime = value; }
    }

    private int _iAttachLiveTime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"iAttachLiveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iAttachLiveTime
    {
      get { return _iAttachLiveTime; }
      set { _iAttachLiveTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_FetchMailNum_Response")]
  public partial class MailDB_FetchMailNum_Response : global::ProtoBuf.IExtensible
  {
    public MailDB_FetchMailNum_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }

    private int _iUin = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iUin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUin
    {
      get { return _iUin; }
      set { _iUin = value; }
    }

    private int _iRole = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iRole", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRole
    {
      get { return _iRole; }
      set { _iRole = value; }
    }

    private int _iMailNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"iMailNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iMailNum
    {
      get { return _iMailNum; }
      set { _iMailNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_CreateNewMail_Request")]
  public partial class MailDB_CreateNewMail_Request : global::ProtoBuf.IExtensible
  {
    public MailDB_CreateNewMail_Request() {}
    

    private OneMail _stMail = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"stMail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OneMail stMail
    {
      get { return _stMail; }
      set { _stMail = value; }
    }

    private int _iNormalLiveTime = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iNormalLiveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iNormalLiveTime
    {
      get { return _iNormalLiveTime; }
      set { _iNormalLiveTime = value; }
    }

    private int _iAttachLiveTime = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iAttachLiveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iAttachLiveTime
    {
      get { return _iAttachLiveTime; }
      set { _iAttachLiveTime = value; }
    }

    private int _iMaxMailNum = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"iMaxMailNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iMaxMailNum
    {
      get { return _iMaxMailNum; }
      set { _iMaxMailNum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_CreateNewMail_Response")]
  public partial class MailDB_CreateNewMail_Response : global::ProtoBuf.IExtensible
  {
    public MailDB_CreateNewMail_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }

    private OneMail _stMail = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stMail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OneMail stMail
    {
      get { return _stMail; }
      set { _stMail = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_UpdateMail_Request")]
  public partial class MailDB_UpdateMail_Request : global::ProtoBuf.IExtensible
  {
    public MailDB_UpdateMail_Request() {}
    

    private int _iUpdateType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iUpdateType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUpdateType
    {
      get { return _iUpdateType; }
      set { _iUpdateType = value; }
    }

    private int _iUpdateParam = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iUpdateParam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUpdateParam
    {
      get { return _iUpdateParam; }
      set { _iUpdateParam = value; }
    }

    private OneMail _stMail = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"stMail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OneMail stMail
    {
      get { return _stMail; }
      set { _stMail = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_UpdateMail_Response")]
  public partial class MailDB_UpdateMail_Response : global::ProtoBuf.IExtensible
  {
    public MailDB_UpdateMail_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }

    private int _iUpdateType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iUpdateType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUpdateType
    {
      get { return _iUpdateType; }
      set { _iUpdateType = value; }
    }

    private int _iUpdateParam = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iUpdateParam", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUpdateParam
    {
      get { return _iUpdateParam; }
      set { _iUpdateParam = value; }
    }

    private OneMail _stMail = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stMail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OneMail stMail
    {
      get { return _stMail; }
      set { _stMail = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_GMQueryMail_Request")]
  public partial class MailDB_GMQueryMail_Request : global::ProtoBuf.IExtensible
  {
    public MailDB_GMQueryMail_Request() {}
    

    private int _iMailID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iMailID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iMailID
    {
      get { return _iMailID; }
      set { _iMailID = value; }
    }

    private int _iZoneID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iZoneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iZoneID
    {
      get { return _iZoneID; }
      set { _iZoneID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_GMQueryMail_Response")]
  public partial class MailDB_GMQueryMail_Response : global::ProtoBuf.IExtensible
  {
    public MailDB_GMQueryMail_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }

    private int _iZoneID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iZoneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iZoneID
    {
      get { return _iZoneID; }
      set { _iZoneID = value; }
    }
    private readonly global::System.Collections.Generic.List<OneMail> _stMailList = new global::System.Collections.Generic.List<OneMail>();
    [global::ProtoBuf.ProtoMember(3, Name=@"stMailList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OneMail> stMailList
    {
      get { return _stMailList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_InsertNewMailGM_Request")]
  public partial class MailDB_InsertNewMailGM_Request : global::ProtoBuf.IExtensible
  {
    public MailDB_InsertNewMailGM_Request() {}
    

    private int _iZoneID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iZoneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iZoneID
    {
      get { return _iZoneID; }
      set { _iZoneID = value; }
    }

    private OneMail _stMail = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stMail", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OneMail stMail
    {
      get { return _stMail; }
      set { _stMail = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailDB_InsertNewMailGM_Response")]
  public partial class MailDB_InsertNewMailGM_Response : global::ProtoBuf.IExtensible
  {
    public MailDB_InsertNewMailGM_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }

    private int _iZoneID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iZoneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iZoneID
    {
      get { return _iZoneID; }
      set { _iZoneID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mail_RevokeMail_Request")]
  public partial class Mail_RevokeMail_Request : global::ProtoBuf.IExtensible
  {
    public Mail_RevokeMail_Request() {}
    

    private int _iZoneID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iZoneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iZoneID
    {
      get { return _iZoneID; }
      set { _iZoneID = value; }
    }

    private int _iRevokeId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iRevokeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRevokeId
    {
      get { return _iRevokeId; }
      set { _iRevokeId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MailDBUpdateType")]
    public enum MailDBUpdateType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"MailDB_UpdateAttachmentTag", Value=1)]
      MailDB_UpdateAttachmentTag = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MailDB_UpdateReadTag", Value=2)]
      MailDB_UpdateReadTag = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MailDB_UpdateDelTag", Value=3)]
      MailDB_UpdateDelTag = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MailDB_UpdateAll", Value=4)]
      MailDB_UpdateAll = 4
    }
  
}