//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GameProtocol.Common.proto
namespace GameProto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneInfo")]
  public partial class ZoneInfo : global::ProtoBuf.IExtensible
  {
    public ZoneInfo() {}
    

    private uint _uZoneID = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uZoneID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uZoneID
    {
      get { return _uZoneID; }
      set { _uZoneID = value; }
    }

    private string _strZoneName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"strZoneName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strZoneName
    {
      get { return _strZoneName; }
      set { _strZoneName = value; }
    }

    private uint _uZoneState = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uZoneState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uZoneState
    {
      get { return _uZoneState; }
      set { _uZoneState = value; }
    }

    private string _strZoneIP = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"strZoneIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strZoneIP
    {
      get { return _strZoneIP; }
      set { _strZoneIP = value; }
    }

    private uint _uZonePort = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"uZonePort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uZonePort
    {
      get { return _uZonePort; }
      set { _uZonePort = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ZoneList")]
  public partial class ZoneList : global::ProtoBuf.IExtensible
  {
    public ZoneList() {}
    
    private readonly global::System.Collections.Generic.List<ZoneInfo> _stZoneInfos = new global::System.Collections.Generic.List<ZoneInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"stZoneInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ZoneInfo> stZoneInfos
    {
      get { return _stZoneInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoleSummary")]
  public partial class RoleSummary : global::ProtoBuf.IExtensible
  {
    public RoleSummary() {}
    

    private uint _uRoleId = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uRoleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uRoleId
    {
      get { return _uRoleId; }
      set { _uRoleId = value; }
    }

    private uint _uProf = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uProf", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uProf
    {
      get { return _uProf; }
      set { _uProf = value; }
    }

    private uint _uGender = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uGender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uGender
    {
      get { return _uGender; }
      set { _uGender = value; }
    }

    private string _strNickName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"strNickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strNickName
    {
      get { return _strNickName; }
      set { _strNickName = value; }
    }

    private uint _uLevel = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"uLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uLevel
    {
      get { return _uLevel; }
      set { _uLevel = value; }
    }

    private int _iWorldId = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"iWorldId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iWorldId
    {
      get { return _iWorldId; }
      set { _iWorldId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogoutServer_Request")]
  public partial class LogoutServer_Request : global::ProtoBuf.IExtensible
  {
    public LogoutServer_Request() {}
    

    private uint _uin = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uin
    {
      get { return _uin; }
      set { _uin = value; }
    }

    private uint _uReason = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uReason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uReason
    {
      get { return _uReason; }
      set { _uReason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogoutServer_Response")]
  public partial class LogoutServer_Response : global::ProtoBuf.IExtensible
  {
    public LogoutServer_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }

    private int _iReason = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iReason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iReason
    {
      get { return _iReason; }
      set { _iReason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddNewName_Request")]
  public partial class AddNewName_Request : global::ProtoBuf.IExtensible
  {
    public AddNewName_Request() {}
    

    private string _strName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"strName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strName
    {
      get { return _strName; }
      set { _strName = value; }
    }

    private int _iType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iType
    {
      get { return _iType; }
      set { _iType = value; }
    }

    private uint _name_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint name_id
    {
      get { return _name_id; }
      set { _name_id = value; }
    }

    private string _name_key = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name_key
    {
      get { return _name_key; }
      set { _name_key = value; }
    }

    private int _uin = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int uin
    {
      get { return _uin; }
      set { _uin = value; }
    }

    private int _iAddType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"iAddType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iAddType
    {
      get { return _iAddType; }
      set { _iAddType = value; }
    }

    private int _iReqAddZone = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"iReqAddZone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iReqAddZone
    {
      get { return _iReqAddZone; }
      set { _iReqAddZone = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddNewName_Response")]
  public partial class AddNewName_Response : global::ProtoBuf.IExtensible
  {
    public AddNewName_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }

    private int _iType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iType
    {
      get { return _iType; }
      set { _iType = value; }
    }

    private uint _name_id = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint name_id
    {
      get { return _name_id; }
      set { _name_id = value; }
    }

    private string _strName = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"strName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strName
    {
      get { return _strName; }
      set { _strName = value; }
    }

    private string _namekey = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"namekey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string namekey
    {
      get { return _namekey; }
      set { _namekey = value; }
    }

    private int _uin = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"uin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int uin
    {
      get { return _uin; }
      set { _uin = value; }
    }

    private int _iAddType = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"iAddType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iAddType
    {
      get { return _iAddType; }
      set { _iAddType = value; }
    }

    private int _iReqAddZone = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"iReqAddZone", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iReqAddZone
    {
      get { return _iReqAddZone; }
      set { _iReqAddZone = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteName_Request")]
  public partial class DeleteName_Request : global::ProtoBuf.IExtensible
  {
    public DeleteName_Request() {}
    

    private string _strName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"strName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strName
    {
      get { return _strName; }
      set { _strName = value; }
    }

    private int _iType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iType
    {
      get { return _iType; }
      set { _iType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeleteName_Response")]
  public partial class DeleteName_Response : global::ProtoBuf.IExtensible
  {
    public DeleteName_Response() {}
    

    private int _iResult = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iResult", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iResult
    {
      get { return _iResult; }
      set { _iResult = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorldBossBase")]
  public partial class WorldBossBase : global::ProtoBuf.IExtensible
  {
    public WorldBossBase() {}
    

    private int _iType = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iType
    {
      get { return _iType; }
      set { _iType = value; }
    }

    private int _iActiveType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iActiveType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iActiveType
    {
      get { return _iActiveType; }
      set { _iActiveType = value; }
    }

    private int _iBossBlood = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iBossBlood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iBossBlood
    {
      get { return _iBossBlood; }
      set { _iBossBlood = value; }
    }

    private int _iCurBossBlood = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"iCurBossBlood", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iCurBossBlood
    {
      get { return _iCurBossBlood; }
      set { _iCurBossBlood = value; }
    }

    private int _iBossAttr = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"iBossAttr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iBossAttr
    {
      get { return _iBossAttr; }
      set { _iBossAttr = value; }
    }

    private int _iStartTime = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"iStartTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iStartTime
    {
      get { return _iStartTime; }
      set { _iStartTime = value; }
    }

    private int _iKillTime = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"iKillTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iKillTime
    {
      get { return _iKillTime; }
      set { _iKillTime = value; }
    }

    private int _iBossLv = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"iBossLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iBossLv
    {
      get { return _iBossLv; }
      set { _iBossLv = value; }
    }

    private int _iKillerRoleid = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"iKillerRoleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iKillerRoleid
    {
      get { return _iKillerRoleid; }
      set { _iKillerRoleid = value; }
    }

    private int _iUpdate = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"iUpdate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUpdate
    {
      get { return _iUpdate; }
      set { _iUpdate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorldBossRank")]
  public partial class WorldBossRank : global::ProtoBuf.IExtensible
  {
    public WorldBossRank() {}
    

    private int _iIdx = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"iIdx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iIdx
    {
      get { return _iIdx; }
      set { _iIdx = value; }
    }

    private int _iRoleid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"iRoleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRoleid
    {
      get { return _iRoleid; }
      set { _iRoleid = value; }
    }

    private string _strName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"strName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string strName
    {
      get { return _strName; }
      set { _strName = value; }
    }

    private int _iRoleLv = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"iRoleLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iRoleLv
    {
      get { return _iRoleLv; }
      set { _iRoleLv = value; }
    }

    private int _iFightValue = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"iFightValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iFightValue
    {
      get { return _iFightValue; }
      set { _iFightValue = value; }
    }

    private int _iPicid = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"iPicid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iPicid
    {
      get { return _iPicid; }
      set { _iPicid = value; }
    }

    private int _iVipLv = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"iVipLv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iVipLv
    {
      get { return _iVipLv; }
      set { _iVipLv = value; }
    }

    private int _iTalian = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"iTalian", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iTalian
    {
      get { return _iTalian; }
      set { _iTalian = value; }
    }

    private int _iTotalHurt = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"iTotalHurt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iTotalHurt
    {
      get { return _iTotalHurt; }
      set { _iTotalHurt = value; }
    }

    private int _iUpdate = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"iUpdate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iUpdate
    {
      get { return _iUpdate; }
      set { _iUpdate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"enNameType")]
    public enum enNameType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_NAME_TYPE_INVALID", Value=0)]
      EN_NAME_TYPE_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_NAME_TYPE_ROLE", Value=1)]
      EN_NAME_TYPE_ROLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_NAME_TYPE_GUILD", Value=2)]
      EN_NAME_TYPE_GUILD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_NAME_TYPE_MAX", Value=3)]
      EN_NAME_TYPE_MAX = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AddNameType")]
    public enum AddNameType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddNameType_NewRole", Value=0)]
      AddNameType_NewRole = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddNameType_ChangeName", Value=1)]
      AddNameType_ChangeName = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AddNameType_NewGuild", Value=2)]
      AddNameType_NewGuild = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eErrResult")]
    public enum eErrResult
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_ERR_INVALID", Value=0)]
      EN_ERR_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_ERR_AUTH_EXISIT", Value=1)]
      EN_ERR_AUTH_EXISIT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_ERR_AUTH_BADNAME", Value=2)]
      EN_ERR_AUTH_BADNAME = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_ERR_AUTH_LOGIN", Value=3)]
      EN_ERR_AUTH_LOGIN = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_ERR_ACTIVECODE_USED", Value=4)]
      EN_ERR_ACTIVECODE_USED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_ERR_ACTIVECODE_ERROR", Value=5)]
      EN_ERR_ACTIVECODE_ERROR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_ERR_MAX", Value=6)]
      EN_ERR_MAX = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"eWorldBossType")]
    public enum eWorldBossType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_LAST_KA", Value=1)]
      EN_LAST_KA = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_LAST_KAI", Value=2)]
      EN_LAST_KAI = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EN_CURRENT_BOSS", Value=3)]
      EN_CURRENT_BOSS = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SourceLogType")]
    public enum SourceLogType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_VAILED_TYPE", Value=0)]
      LOG_VAILED_TYPE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_TALENT_OPEN", Value=1)]
      LOG_TALENT_OPEN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_CHANGE_NAME", Value=2)]
      LOG_CHANGE_NAME = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_REFINE_EQUIP", Value=3)]
      LOG_REFINE_EQUIP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_DECOMPOSE_EQUIP", Value=4)]
      LOG_DECOMPOSE_EQUIP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_DECOMPOSE_TRINKET", Value=5)]
      LOG_DECOMPOSE_TRINKET = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_EXTRACT_HERO", Value=6)]
      LOG_EXTRACT_HERO = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_GRADEUPSKILL_HERO", Value=7)]
      LOG_GRADEUPSKILL_HERO = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_EXTRACT_SOUL", Value=8)]
      LOG_EXTRACT_SOUL = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_GRADEUP_HERO", Value=9)]
      LOG_GRADEUP_HERO = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_RECIV_HERO", Value=10)]
      LOG_RECIV_HERO = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_EMPLOY_HERO", Value=11)]
      LOG_EMPLOY_HERO = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_CHARFGE_ROLE", Value=12)]
      LOG_CHARFGE_ROLE = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_RESETCROSS", Value=13)]
      LOG_RESETCROSS = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_CLEAR_CROSSCD", Value=14)]
      LOG_CLEAR_CROSSCD = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_PVP", Value=15)]
      LOG_PVP = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_CHARGE_SYS", Value=16)]
      LOG_CHARGE_SYS = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_FIRSTCHARGE_SYS", Value=17)]
      LOG_FIRSTCHARGE_SYS = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_FETCH_REGIN", Value=18)]
      LOG_FETCH_REGIN = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_REFINE_DAY", Value=19)]
      LOG_REFINE_DAY = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_MAL_BUY", Value=20)]
      LOG_MAL_BUY = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_SHOP_BUY", Value=21)]
      LOG_SHOP_BUY = 21,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_UPDATESHOP_BUY", Value=22)]
      LOG_UPDATESHOP_BUY = 22,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_BLOCK_BAG", Value=23)]
      LOG_BLOCK_BAG = 23,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_USE_THING", Value=24)]
      LOG_USE_THING = 24,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_STREANGEEQUIP", Value=25)]
      LOG_STREANGEEQUIP = 25,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_STRANGE_TRINKET", Value=26)]
      LOG_STRANGE_TRINKET = 26,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_REFINE_TRINKET", Value=27)]
      LOG_REFINE_TRINKET = 27,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_GRADE_SKILL", Value=28)]
      LOG_GRADE_SKILL = 28,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_EXTRA_SOUL", Value=29)]
      LOG_EXTRA_SOUL = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_OPEN_MINE", Value=30)]
      LOG_OPEN_MINE = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_SPEED_MINE", Value=31)]
      LOG_SPEED_MINE = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_MINE_QUALITY", Value=32)]
      LOG_MINE_QUALITY = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_UPDATESTEP_HERO", Value=33)]
      LOG_UPDATESTEP_HERO = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_PVPSHOP", Value=34)]
      LOG_PVPSHOP = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_FRESH_MATRIAL", Value=35)]
      LOG_FRESH_MATRIAL = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_FRESH_REWARD", Value=36)]
      LOG_FRESH_REWARD = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_DOUBLE_REWARD", Value=37)]
      LOG_DOUBLE_REWARD = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_WORLD_BOSS", Value=38)]
      LOG_WORLD_BOSS = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_MINE_GOLD", Value=39)]
      LOG_MINE_GOLD = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_TRINKET_BOX", Value=40)]
      LOG_TRINKET_BOX = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_SOUL_ALTARS", Value=41)]
      LOG_SOUL_ALTARS = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_MASTER_RESULT", Value=42)]
      LOG_MASTER_RESULT = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_TREASURE", Value=43)]
      LOG_TREASURE = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_DRAGON", Value=44)]
      LOG_DRAGON = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_TOWER", Value=45)]
      LOG_TOWER = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_COURAGE", Value=46)]
      LOG_COURAGE = 46,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_GUILD_RECORD", Value=47)]
      LOG_GUILD_RECORD = 47,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_ACHIEVEMENT", Value=48)]
      LOG_ACHIEVEMENT = 48,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_TASKEVERYDAY", Value=49)]
      LOG_TASKEVERYDAY = 49,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_MELTER", Value=50)]
      LOG_MELTER = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_ENERGY_BUY", Value=51)]
      LOG_ENERGY_BUY = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_TREASURE_BUY", Value=52)]
      LOG_TREASURE_BUY = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_RESETBOSS", Value=53)]
      LOG_RESETBOSS = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_BLACKMARKET", Value=54)]
      LOG_BLACKMARKET = 54,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_HEROCOMPSITE_RECORDE", Value=55)]
      LOG_HEROCOMPSITE_RECORDE = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_TRINKETCOMPSITE_RECORDE", Value=56)]
      LOG_TRINKETCOMPSITE_RECORDE = 56,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_TREASURE_COUNT", Value=57)]
      LOG_TREASURE_COUNT = 57,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_REWARD_LEVEL", Value=58)]
      LOG_REWARD_LEVEL = 58,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_REWARD_BACK", Value=59)]
      LOG_REWARD_BACK = 59,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_LOGIN_REWARD", Value=60)]
      LOG_LOGIN_REWARD = 60,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_BLACKMARKET_FRESH", Value=61)]
      LOG_BLACKMARKET_FRESH = 61,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_RESETCONQTOWER", Value=62)]
      LOG_RESETCONQTOWER = 62,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_SWEEPCONQTOWER", Value=63)]
      LOG_SWEEPCONQTOWER = 63,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_SWEEPCROSS", Value=64)]
      LOG_SWEEPCROSS = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_MASTER_SORCE", Value=65)]
      LOG_MASTER_SORCE = 65,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_MASTER_RANK", Value=67)]
      LOG_MASTER_RANK = 67,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_TREASURE_RESULT", Value=68)]
      LOG_TREASURE_RESULT = 68,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_TREASURE_CHIPS", Value=69)]
      LOG_TREASURE_CHIPS = 69,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_TREASURE_CHIPSEXCHANGE", Value=70)]
      LOG_TREASURE_CHIPSEXCHANGE = 70,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_MASTER_ADD", Value=71)]
      LOG_MASTER_ADD = 71,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_GROP_PLAN", Value=72)]
      LOG_GROP_PLAN = 72,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_GROP_GETREWARD", Value=73)]
      LOG_GROP_GETREWARD = 73,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_ACTEXCHANGE", Value=74)]
      LOG_ACTEXCHANGE = 74,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_ARCHFUNC", Value=75)]
      LOG_ARCHFUNC = 75,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_EXTRACTBESTHERO_ONE", Value=76)]
      LOG_EXTRACTBESTHERO_ONE = 76,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_RechargeFeedBack", Value=77)]
      LOG_RechargeFeedBack = 77,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_CostFeedBack", Value=78)]
      LOG_CostFeedBack = 78,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_EXTRACTBESTHERO_TEN", Value=79)]
      LOG_EXTRACTBESTHERO_TEN = 79,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_PINSTANCE_STARREWARD", Value=80)]
      LOG_PINSTANCE_STARREWARD = 80,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_HERO_STEPUP", Value=81)]
      LOG_HERO_STEPUP = 81,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_GETREWARD_TAILOR", Value=82)]
      LOG_GETREWARD_TAILOR = 82,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_GETREWARD_MAIL", Value=83)]
      LOG_GETREWARD_MAIL = 83,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_LIMIT_BUY", Value=84)]
      LOG_LIMIT_BUY = 84,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_CHEESE_BUY", Value=85)]
      LOG_CHEESE_BUY = 85,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_FIGHT_CHEAT", Value=86)]
      LOG_FIGHT_CHEAT = 86,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_BUY_QUALIFYINGTIMES", Value=87)]
      LOG_BUY_QUALIFYINGTIMES = 87,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_POSY_SYSTEM_Common", Value=88)]
      LOG_POSY_SYSTEM_Common = 88,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_POSY_SYSTEM_Diamond", Value=89)]
      LOG_POSY_SYSTEM_Diamond = 89,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_POSY_SYSTEM_Compose", Value=90)]
      LOG_POSY_SYSTEM_Compose = 90,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOG_POSY_SYSTEM_Change", Value=91)]
      LOG_POSY_SYSTEM_Change = 91
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PINSTANCETYPE")]
    public enum PINSTANCETYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PINSTANCETYPE_START", Value=1)]
      PINSTANCETYPE_START = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PINSTANCETYPE_SUCCESS", Value=2)]
      PINSTANCETYPE_SUCCESS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PINSTANCETYPE_FAILED", Value=3)]
      PINSTANCETYPE_FAILED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PINSTANCE_GIVEUP", Value=4)]
      PINSTANCE_GIVEUP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PINSTANCE_SWEEP", Value=5)]
      PINSTANCE_SWEEP = 5
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"NODERECODE")]
    public enum NODERECODE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGTYPE_REGISTERUSER", Value=1)]
      LOGTYPE_REGISTERUSER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGTYPE_REGISTERFAIL", Value=2)]
      LOGTYPE_REGISTERFAIL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGTYPE_CREATEROLE", Value=3)]
      LOGTYPE_CREATEROLE = 3
    }
  
}